#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground and flyhi
#=================================================

name: Build_Lienol_OP_x86_64

on: 
  release:
    types: [published]

  push:
  #  branches: 
  #    - master
    tags:
      - v1.*

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex node-uglify gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      env: 
        REPO_URL: https://github.com/Lienol/openwrt.git
        REPO_BRANCH: dev-19.07
      run: |
        git clone  $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        git checkout b68a89518bebdca5d5ff400d870ef1fc1e059815

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        #cp feeds.conf.default feeds.conf
        #echo -e '\nsrc-git custom https://github.com/k-szuster/luci-access-control-package.git' >> feeds.conf
        #cat feeds.conf
        #echo 'start feeds update custom'
        ./scripts/feeds update custom 
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        # Add other app
        # git clone https://github.com/ozon/luci-app-ttyd.git package/feeds/luci-app-ttyd
    
    - name: add docker support
      working-directory: ./openwrt
      run: |
        mkdir -p package/luci-lib-docker && \
        wget https://raw.githubusercontent.com/lisaac/luci-lib-docker/master/Makefile -O package/luci-lib-docker/Makefile
        mkdir -p package/luci-app-dockerman && \
        wget https://raw.githubusercontent.com/lisaac/luci-app-dockerman/master/Makefile -O package/luci-app-dockerman/Makefile
        #compile package only
        #make package/luci-lib-jsonc/compile V=99
        #make package/luci-lib-docker/compile v=99
        #make package/luci-app-dockerman/compile v=99
        
    - name: add openclash support
      working-directory: ./openwrt
      run: |     
        git clone https://github.com/vernesong/OpenClash.git package/luci-app-openclash
        # 编译 po2lmo (如果有po2lmo可跳过)
        pushd package/luci-app-openclash/luci-app-openclash/tools/po2lmo
        make && sudo make install
        popd
        
        
    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: 'lienol_ow_x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name: Single-thread compile
      if: failure()
      run: |
          cd openwrt
          make -j1 V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Lienol OpenWrt
        path: openwrt/bin
